baseurl= "http://kylefeng28.github.io/"
languageCode= "en-US"
title= "kylefeng28"
metaDataFormat= "yaml"
googleAnalytics= "UA-64685214-1"

[author]
name= "Kyle Feng"

[permalinks]
post= "/blog/:year/:month/:day/:title/"

[params]
description= ""
copyright= "© 2015-16 Kyle Feng"

# TODO switch to yaml
[menu]
	[[menu.main]]
		name = "Blog"
		url = "/blog"
		[[menu.main]]
		name = "Playground"
		url = "/playground"
		[[menu.main]]
		name = "About"
		url = "/about"

# from hexo
# date_format: YYYY-MM-DD
# time_format: HH:mm:ss
# [params.menu]
#  Playground: /playground
#  About: /about
#  Archives: /archives
#  rss: /atom.xml
