baseurl: "https://kylefeng28.github.io/"
languageCode: "en-US"
title: "kylefeng28"
metaDataFormat: "yaml"
googleAnalytics: "UA-64685214-1"

author:
  name: "Kyle Feng"

permalinks:
  post: "/blog/:year/:month/:day/:title/"

params:
  description: ""
  copyright: "© 2015-17 Kyle Feng"

menu:
  main:
    - { name: "About", url: "/about", weight: 1 }
    # - { name: "Blog", url: "/blog", weight: 2 }
    - { name: "Playground", url: "/playground", weight: 3 }

# from hexo
# date_format: YYYY-MM-DD
# time_format: HH:mm:ss
